# Generated by Django 4.0 on 2022-01-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte_SCF',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rubrique', models.CharField(max_length=50)),
                ('pos', models.PositiveIntegerField()),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.compte_scf')),
            ],
        ),
    ]
