# Generated by Django 4.0 on 2022-01-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_compte_scf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte_scf',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.compte_scf'),
        ),
    ]
