# Generated by Django 4.0 on 2022-01-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_unite_has_compte_chapire_scf_pos_7_chapitre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte_has_montant',
            name='commentaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.commentaire'),
        ),
        migrations.AlterField(
            model_name='compte_has_montant',
            name='vld_cadre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compte_has_montant',
            name='vld_chef_dep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compte_has_montant',
            name='vld_sous_dir',
            field=models.BooleanField(default=False),
        ),
    ]
