# Generated by Django 4.0 on 2022-01-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_compte_has_montant_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte_has_montant',
            name='unite_compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montants', to='main.unite_has_compte'),
        ),
    ]
