# Generated by Django 4.0 on 2022-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_compte_has_montant_unite_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interim',
            name='date_debut',
            field=models.DateField(auto_now=True),
        ),
    ]
