# Generated by Django 4.0 on 2022-01-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_interim_date_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='importance',
            field=models.CharField(choices=[('F', 'Faible'), ('M', 'Moyenne'), ('C', 'Critique')], default='F', max_length=50),
        ),
    ]
