# Generated by Django 4.0 on 2022-01-21 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_commentaire_importance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_Budgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('annee', models.IntegerField()),
                ('type_bdg', models.CharField(choices=[('PROPOS', 'Budget de proposition'), ('REUN', 'Budget de Réunion'), ('NOTIF', 'Budget notifié')], max_length=50)),
                ('lancement', models.BooleanField(default=False)),
                ('cloture', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='compte_has_montant',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='compte_has_montant',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='compte_has_montant',
            name='monnaie',
        ),
        migrations.RemoveField(
            model_name='unite_has_compte',
            name='existe',
        ),
        migrations.AddField(
            model_name='cadre_has_unite',
            name='code',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentaire',
            name='comment_type',
            field=models.CharField(choices=[('F', 'Faible'), ('M', 'Moyenne'), ('C', 'Critique')], default='M', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='commentaire_cloture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloture_comm', to='main.commentaire'),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='commentaire_montant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montants_comm', to='main.commentaire'),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='montant_cloture',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unite_has_compte',
            name='code',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unite_has_compte',
            name='monnaie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.monnaie'),
        ),
        migrations.AlterField(
            model_name='unite_has_compte',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_comptes_added', to='main.user'),
        ),
        migrations.AlterField(
            model_name='unite_has_compte',
            name='reseau_compte',
            field=models.CharField(choices=[('INT', 'Internationle'), ('DOM', 'Domestique'), ('ALL', 'All')], max_length=50),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='annee_budgetaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='montants', to='main.annee_budgetaire'),
            preserve_default=False,
        ),
    ]
