# Generated by Django 4.0 on 2022-01-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_commentaire_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='importance',
            field=models.CharField(choices=[('A', 'Aucun'), ('F', 'Faible'), ('M', 'Moyenne'), ('C', 'Critique')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='text',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AlterField(
            model_name='compte_has_montant',
            name='commentaire_cloture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloture_comm', to='main.commentaire'),
        ),
        migrations.AlterField(
            model_name='compte_has_montant',
            name='commentaire_montant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montants_comm', to='main.commentaire'),
        ),
        migrations.AlterField(
            model_name='unite_has_compte',
            name='reseau_compte',
            field=models.CharField(choices=[('INT', 'Internationle'), ('DOM', 'Domestique'), ('ALL', 'All')], default='ALL', max_length=50),
        ),
    ]
