# Generated by Django 4.0 on 2022-02-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_commentaire_importance_alter_commentaire_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte_has_montant',
            name='aout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='avril',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='decembre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='fevrier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='janvier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='juillet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='juin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='mars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='novembre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='octobre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='septemre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='type_decoupage',
            field=models.CharField(choices=[('MS', 'Mensuelles'), ('BM', 'Bimestriel'), ('TR', 'Trimestriel'), ('SM', 'Semestriel'), ('AU', 'Autre')], default='MS', max_length=50),
        ),
    ]
