# Generated by Django 4.0 on 2022-02-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_compte_has_montant_aout_compte_has_montant_avril_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte_has_montant',
            name='type_decoupage',
            field=models.CharField(blank=True, choices=[('MS', 'Mensuelles'), ('BM', 'Bimestriel'), ('TR', 'Trimestriel'), ('SM', 'Semestriel'), ('AU', 'Autre')], default='MS', max_length=50, null=True),
        ),
    ]
