# Generated by Django 4.0 on 2022-02-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_compte_has_montant_type_decoupage'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte_has_montant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='edition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='type_maj',
            field=models.CharField(blank=True, choices=[('A', 'Actualisation'), ('R', 'Réajustement'), ('N', 'Initial')], default='N', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='annee_budgetaire',
            name='type_bdg',
            field=models.CharField(choices=[('PROPOS', 'Budget de proposition'), ('REUN', 'Budget de Réunion'), ('NOTIF', 'Budget notifié'), ('CTRL', 'Budget de contrôle'), ('RELS', 'Budget réalisation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='compte_has_montant',
            name='type_bdg',
            field=models.CharField(choices=[('PROPOS', 'Budget de proposition'), ('REUN', 'Budget de Réunion'), ('NOTIF', 'Budget notifié'), ('CTRL', 'Budget de contrôle'), ('RELS', 'Budget réalisation')], max_length=50),
        ),
    ]
