# Generated by Django 4.0 on 2022-02-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_compte_has_montant_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte_has_montant',
            name='validation_mens',
            field=models.CharField(blank=True, choices=[('CADRE', 'Cadre Budget'), ('CHEFD', 'Chef Département'), ('CHEFDPI', 'Chef Département DZ P/I'), ('CHEFDPI', 'Chef Département ET P/I'), ('SOUSD', 'Sous Directeur'), ('SOUSDPI', 'Sous Directeur P/I')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='vld_mens_cadre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='vld_mens_chef_dep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compte_has_montant',
            name='vld_mens_sous_dir',
            field=models.BooleanField(default=False),
        ),
    ]
