# Generated by Django 4.0 on 2022-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_compte_has_montant_mens_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte_has_montant',
            old_name='commentaire_cloture',
            new_name='commentaire_mens',
        ),
        migrations.AlterField(
            model_name='compte_has_montant',
            name='type_decoupage',
            field=models.CharField(blank=True, choices=[('MS', 'Mensuel'), ('BM', 'Bimensuel'), ('TR', 'Trimestriel'), ('SM', 'Semestriel'), ('AU', 'Autre')], default='MS', max_length=50, null=True),
        ),
    ]
