# Generated by Django 4.0 on 2022-03-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_compte_has_montant_edition_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte_has_montant',
            name='edition_v',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
