# Generated by Django 4.0 on 2022-03-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_compte_has_montant_vld_controle_sous_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite_has_compte',
            name='monnaie',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.monnaie'),
        ),
        migrations.AlterField(
            model_name='unite_has_compte',
            name='regle_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unite_regle', to='main.unite'),
        ),
    ]
