# Generated by Django 4.0 on 2022-03-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_unite_has_compte_monnaie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monnaie',
            name='code_num',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='code_num',
        ),
        migrations.AlterField(
            model_name='monnaie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unite',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unite',
            name='lib',
            field=models.CharField(max_length=150),
        ),
    ]
