# Generated by Django 4.0 on 2022-03-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_monnaie_code_num_remove_unite_code_num_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='annee_budgetaire',
            table='Annee_Budgetaire',
        ),
        migrations.AlterModelTable(
            name='cadre_has_unite',
            table='Cadre_has_Unite',
        ),
        migrations.AlterModelTable(
            name='chapitre',
            table='Chapitre',
        ),
        migrations.AlterModelTable(
            name='commentaire',
            table='Commentaire',
        ),
        migrations.AlterModelTable(
            name='compte_has_montant',
            table='Compte_has_Montant',
        ),
        migrations.AlterModelTable(
            name='departement',
            table='Departement',
        ),
        migrations.AlterModelTable(
            name='historique',
            table='Historique',
        ),
        migrations.AlterModelTable(
            name='interim',
            table='Interim',
        ),
        migrations.AlterModelTable(
            name='monnaie',
            table='Monnaie',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
        migrations.AlterModelTable(
            name='pays',
            table='Pays',
        ),
        migrations.AlterModelTable(
            name='reception',
            table='Reception',
        ),
        migrations.AlterModelTable(
            name='scf_pos_1',
            table='SCF_Pos_1',
        ),
        migrations.AlterModelTable(
            name='scf_pos_2',
            table='SCF_Pos_2',
        ),
        migrations.AlterModelTable(
            name='scf_pos_3',
            table='SCF_Pos_3',
        ),
        migrations.AlterModelTable(
            name='scf_pos_6',
            table='SCF_Pos_6',
        ),
        migrations.AlterModelTable(
            name='scf_pos_7',
            table='SCF_Pos_7',
        ),
        migrations.AlterModelTable(
            name='taux_de_change',
            table='Taux_de_change',
        ),
        migrations.AlterModelTable(
            name='unite',
            table='Unite',
        ),
        migrations.AlterModelTable(
            name='unite_has_compte',
            table='Unite_has_Compte',
        ),
    ]
