# Generated by Django 4.0 on 2022-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_annee_budgetaire_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monnaie',
            name='code_alpha',
            field=models.CharField(max_length=200),
        ),
    ]
