# Generated by Django 4.0 on 2022-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_monnaie_code_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monnaie',
            name='lib',
            field=models.TextField(),
        ),
    ]
