# Generated by Django 4.0 on 2022-03-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_monnaie_lib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unite',
            name='region',
            field=models.CharField(choices=[('1', 'Internationle'), ('0', 'Domestique')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='unite',
            name='reseau_unite',
            field=models.CharField(choices=[('Algerie', 'Algérie'), ('France', 'France'), ('Europe', 'Europe'), ('MMO', 'Maghreb et Moyen Orient'), ('Afrique', 'Afrique'), ('Amerique', 'Amérique'), ('Asie', 'Asie')], default='Algerie', max_length=50),
        ),
        migrations.AlterField(
            model_name='unite_has_compte',
            name='monnaie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.monnaie'),
        ),
    ]
