# Generated by Django 4.0 on 2022-03-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_departement_id_alter_unite_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
