# Generated by Django 4.0 on 2022-04-17 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_departement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte_has_montant',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='unite_has_compte',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_comptes_added', to='main.user'),
        ),
        migrations.AlterField(
            model_name='unite_has_compte',
            name='reseau_compte',
            field=models.CharField(choices=[('I', 'International'), ('D', 'Domestique'), ('A', 'All')], default='ALL', max_length=50),
        ),
    ]
